keys:
  - &primary age1x6muzwc0t3qnlvds0k72npsvuf2vg5lt27g9we2vrtg6gj3cjfus62jtnm

  - &nixy age19yyst6n84e0mww2s3ffws22wxv33nhhlt9e73s5wuh3mhqgt55vq6t7glj

creation_rules:
  - path_regex: "modules/users/job/secrets.yaml$"
    key_groups:
      - age:
          - *primary
          - *nixy
  - path_regex: "modules/users/root/secrets.yaml$"
    key_groups:
      - age:
          - *primary
          - *nixy
